version: "3"

services:
  palindromes:
    build:
      context: palindromes
      dockerfile: .Dockerfile
    ports:
      - "3000:3000"

  postgres:
    image: postgres:10.4-alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=palindromes
      - POSTGRES_USER=palindromes
      - POSTGRES_PASSWORD=palindromes



networks:
  palindromes:
    internal: true